// <auto-generated />
namespace FilmKupriyanov.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FixUserContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixUserContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201906170801503_FixUserContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
